### PR TITLE
:memo: install and config

### PR DESCRIPTION
**Pull request by jdubuisson**
Adding some documentation : installation & configuration steps.

Let me know if it is incorrect or incomplete.

### CODE REVIEW

**Comment by ekyna** [comment]
Hi @jdubuisson

My apologies for the absence of documentation.

I made this bundle to integrate the [PayumMonetico](https://github.com/ekyna/PayumMonetico) component with EkynaCommerceBundle, but i'm not sure it will help you with another eCommerce solution :s

It uses [DependencyInjection\Compiler\RegisterGatewayPass](https://github.com/ekyna/PayumMoneticoBundle/blob/master/src/DependencyInjection/Compiler/RegisterGatewayPass.php) to register the Monetico gateway factory to payum. You should be able to use the gateway without the needs to configure PayumBundle with YAML.
```php
// Try this ?
$gateway = $this->get('payum')->getGateway('monetico');
```
But you will need to develop your own ConvertPaymentAction ([example](https://github.com/ekyna/PayumMoneticoBundle/blob/master/src/Action/CommerceConvertAction.php)) and a custom NotifyAction (controller) for IPNs, because Payum uses tokens to identify payments but Monetico does not allow to configure specific IPN urls for each payments. Try something like that:
```php
public function notifyAction(Request $request)
{
    // Get the reference you set in your ConvertAction
    if (null === $reference = $request->request->get('reference')) {
        throw new NotFoundHttpException();
    }

    // Find your payment entity
    $payment = $this
        ->get('acme.repository.payment')
        ->findOneBy(['number' => $reference]);

    if (null === $payment) {
        throw new NotFoundHttpException();
    }

    $payum = $this->get('payum');

    // Execute notify & status actions.
    $gateway = $payum->getGateway('monetico');
    $gateway->execute(new Notify($payment));
    $gateway->execute(new GetHumanStatus($payment));

    // Get the payment identity
    $identity = $payum->getStorage($payment)->identify($payment);

    // Invalidate payment tokens
    $tokens = $payum->getTokenStorage()->findBy([
        'details' => $identity,
    ]);
    foreach ($tokens as $token) {
        $payum->getHttpRequestVerifier()->invalidate($token);
    }

    // Return expected response
    return new Response(\Ekyna\Component\Payum\Monetico\Api\Api::NOTIFY_SUCCESS);
}
```
You'll have to tell which absolute URL you want to use to Monetico technicians (yes, boring).

I hope this will help you ! ;)

**Comment by jdubuisson** [comment]
Thanks for your answer @ekyna !

Your are right regarding the compiler pass : the YAML configuration is redundant.

The bundle integrates with [Sylius](https://github.com/Sylius/Sylius) easily : the compiler pass sets up the Gateway with the provided parameters and it seems to be enough to generate a proper request to Monetico's servers.
I am waiting for test credentials, so I did not go any further. Based on your message, some more work is required, so I'll close this PR for now.

Once I get the end-to-end payment working with Sylius, I'll look into publishing the code, either here or into a dedicated repo.

**Comment by Prometee** [comment]
@jdubuisson do you finally finish your implementation ?
If you want to look at mine : [Prometee/SyliusPayumMoneticoPlugin](https://github.com/Prometee/SyliusPayumMoneticoPlugin)
Maybe you could give me some feedback about your integration in Sylius.

All is there : the form to configure it in the admin, the correct ConvertAction (prepend) and the NotifyController to handle the uniq CGI return URL.
It works for me with my latest tests with a Monetico TEST mode account, let me know if it could work for you too and feel free to create a push request ;)

I know there is no test yet and no documentation, but I need to focus on other parts of my current project :$ I plan to add it on January

**Comment by Prometee** [comment]
There is a problem with the fact that Monetico allow repayment after failed payment.

1. A payment security token and a payment are created in the database
2. The customer is redirect to the Monetico portal and he fill up the payment form
3. Payment fail (so CGI URL is called and payment status change to failed)
4. He click on "retry payment" link
5. Payment successful (eg: a new call to the CGI URL is made)
6. The customer click on "go back to the store"
7. 404 page (because this capture token URL don't exists) and meanwhile a new payment for the same order has been created but there is no payment security token to refer to

is there a way to handle this process ? Or this is a Sylius issue ?

**Comment by ekyna** [comment]
Hi @Prometee 

I'm not using Sylius but i'm glad you made your monetico plugin for it.

I did not encountered this 404 error so i'll need to make further investigation, but Payum security tokens are deleted by this call:

```php
/** @var \Payum\Core\Payum $payum */
$payum->getHttpRequestVerifier()->invalidate($token);
```
You should look for it and find a way to delay it.

**Pull request closed without merging**
